FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY entrypoint.sh ./  

RUN yarn install

COPY . .
COPY .env /usr/src/app/.env

RUN chmod +x /usr/src/app
RUN chmod +x /usr/src/app/entrypoint.sh

RUN npx prisma generate --schema=/usr/src/app/src/infra/database/prisma/schema.prisma 

RUN yarn build

ENTRYPOINT [ "/usr/src/app/entrypoint.sh", "yarn", "start:prod" ]
